/* eslint-disable prettier/prettier */
export default {
	auth: {
		OTPScreen: "otp-screen",
		SignupScreen: "signup-screen",
		SignInScreen: "sign-in-screen",
		TermsOfService: "terms-of-service",
		OnboardingScreen: "onboarding-screen",
		EnterRefferCodeScreen: "enter-reffer-code",
		EnterDetailsScreen: "enter-details-screen",
		EnterProfessionScreen: "enter-profession",
		PartOfOrgScreen: "part-of-org",
	},
	configuration: {},
	app: {
		IndividualSplashScreen: "individual-splash-screen",
		BottomTab: "bottom-tab",
		HomeScreen: "home-screen",
		ServiceScreen: "service-screen",
		ProfileScreen: "profile-screen",
		ChangeLanguage: "change-language-screen",
		EditProfile: "edit-profile-screen",
		AddBankScreen: "add-bank-screen",
		ReferFriendScreen: "refer-friend-screen",
		ApplyCouponScreen: "apply-coupon-screen",
		PreviousCureScreen: "previous-cure-screen",
		DemoVideosScreen: "demo-videos-screen",
		ReferCaseScreen: "refer-case-screen",
		LiveReferCaseScreen: "live-refer-case-screen",
	},
};
