/* eslint-disable prettier/prettier */
export default {
	colorWhite: '#FFFFFF',
	colorBrand1: '#8A86F1',
	colorBrand2: '#FB8315',
	colorBrandLight1: '#E3DFFF',
	colorDark1: '#282828',
	colorDark2: '#4E4E4E',
	colorGrey1: '#D9D9D9',
	colorGrey2: '#2E2E2E',
	colorGreyLight1: '#F8F8F8',
	colorGreyLight2: '#979797',
	colorRed1: '#F55459',
	buttonBlue1: '#8A86F1',
	fontPoppinsBold: 'Poppins_Bold',
	fontPoppinsThin: 'Poppins_Thin',
	fontManropeBold: 'Manrope_Bold',
	fontManropeLight: 'Manrope_Light',
	fontManropeMedium: 'Manrope_Medium',
	fontManropeRegular: 'Manrope_Regular',
	fontManropeSemiBold: 'Manrope_SemiBold',
	fontManropeExtraBold: 'Manrope_ExtraBold',
	fontManropeExtraLight: 'Manrope_ExtraLight',
	fontPoppinsLight: 'Poppins_Light',
	fontPoppinsMedium: 'Poppins_Medium',
	fontPoppinsRegular: 'Poppins_Regular',
	fontPoppinsSemiBold: 'Poppins_SemiBold',
	fontPoppinsExtraBold: 'Poppins_ExtraBold',
	fontPoppinsExtraLight: 'Poppins_ExtraLight',
};
